# Generated by Django 3.1.4 on 2021-01-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamic_data', '0004_menucustomer2'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCustomer3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('specialoffer', models.BooleanField(default=False)),
            ],
        ),
    ]
