# Generated by Django 3.1.4 on 2021-01-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamic_data', '0005_menucustomer3'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('call', models.IntegerField(max_length=12)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
    ]
