# Generated by Django 3.1.4 on 2021-01-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamic_data', '0006_contactdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='call',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
